drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text NOT NULL,
    url VARCHAR NOT NULL,
    description text,
    rating integer
);

insert into bookmarks (title, url, description, rating)
values
('my github', 'https://github.com/JBohme13/', 'a collection of my practice and projects', '5'),
('my linkedin', 'https://www.linkedin.com/in/jordan-bohme-a04973186/', 'a collection of my career achievments', '3'),
('graphQL decumentation', 'https://graphql.org', 'a query framework based on sql', '4'),
('thinkful dashboard', 'thinkful.com', 'my bootcamp home page', '4'),
('google', 'google.com', 'google', '3'),
('codewars home page', 'codewars.com', 'where i practice problem solving', '3'),
('spotify', 'spotify.com', 'where i listen to music', '5'),
('netflix', 'netflix.com', 'where i watch shows', '4'),
('hbo now', 'hbonow.com', 'where i watch movies', '2'),
('booj home page', 'booj.com', 'where i hope to work soon', '5');